/**
 * Expression Number Interpretations
 * Extracted from ExpressionNumberScreen for Bible.md compliance (under 400 lines)
 */

import { NumberSection } from '@/components/numbers/NumberDetailScreen';

export const EXPRESSION_SECTIONS: Record<number, NumberSection[]> = {
  1: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 1 indicates you are meant to be a pioneer in your chosen field. You excel in leadership positions and are drawn to careers where you can initiate new projects, lead teams, and be the first to implement innovative ideas. Your professional destiny involves breaking new ground and inspiring others through your original approach.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Executive leadership abilities\n+Innovative problem-solving\n+Independent work style\n+Pioneering spirit in new ventures\n+Natural confidence in decision-making\n+Ability to inspire and motivate teams\n+Original thinking and creativity',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Entrepreneur and Business Owner: Starting your own ventures allows you to fully express your leadership and innovation.\n\nExecutive Roles: CEO, President, Director positions where you can lead organizations toward new horizons.\n\nInventor/Innovator: Creating new products, services, or systems that change how things are done.\n\nConsultant: Helping other businesses implement new strategies and overcome challenges.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
    {
      id: 'creative-expression',
      title: 'Creative Expression',
      content: 'Your creativity manifests through groundbreaking ideas and original approaches to challenges. You have a gift for seeing possibilities that others miss and turning innovative concepts into reality. Your artistic expressions tend to be bold, original, and trend-setting.',
      icon: '◈',
      type: 'practical',
      level: 2,
    },
    {
      id: 'leadership-style',
      title: 'Leadership Style',
      content: 'You lead by example and prefer to be at the forefront of new initiatives. Your leadership style is direct, confident, and inspiring. You motivate others through your vision and determination, though you may need to develop patience for those who need more time to embrace change.',
      icon: '◉',
      type: 'practical',
      level: 2,
    },
  ],
  2: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 2 reveals your destiny as a natural diplomat and mediator. You excel in careers that involve bringing people together, facilitating cooperation, and creating harmony in professional environments. Your greatest success comes through partnership and collaborative efforts rather than solo endeavors.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional diplomatic skills\n+Natural ability to mediate conflicts\n+Strong emotional intelligence\n+Gift for cooperative teamwork\n+Attention to detail and quality\n+Intuitive understanding of others\n+Patient and supportive nature',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Human Resources: Your natural ability to understand people makes you excellent at managing workplace relationships.\n\nCounseling and Therapy: Helping individuals and couples work through challenges and find harmony.\n\nTeam Coordinator: Facilitating group projects and ensuring smooth collaboration between departments.\n\nDiplomat/Mediator: Resolving conflicts and building bridges between opposing parties.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
    {
      id: 'creative-expression',
      title: 'Creative Expression',
      content: 'Your creativity flows through collaborative projects and harmonious compositions. You excel at bringing together different elements to create something beautiful and balanced. Your artistic work often focuses on themes of unity, peace, and emotional connection.',
      icon: '◈',
      type: 'practical',
      level: 2,
    },
  ],
  3: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 3 marks you as a natural entertainer and communicator. You are destined to inspire, uplift, and bring joy to others through your creative expression. Your professional path involves sharing your gifts of communication, creativity, and optimism with the world.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Outstanding communication skills\n+Natural creativity and artistic ability\n+Gift for inspiring and motivating others\n+Charismatic and engaging personality\n+Ability to see the bright side of situations\n+Talent for self-expression\n+Natural entertainer and performer',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Creative Arts: Writing, acting, music, visual arts where you can express your creativity freely.\n\nMarketing and Communications: Using your persuasive abilities to promote products, ideas, or causes.\n\nTeaching and Training: Inspiring others through education and knowledge sharing.\n\nPublic Speaking: Motivating audiences through presentations, workshops, or entertainment.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
    {
      id: 'creative-expression',
      title: 'Creative Expression',
      content: 'You are a natural creator with multiple talents. Your creativity spans various mediums - writing, speaking, visual arts, music. You have the gift of making complex ideas accessible and inspiring to others. Your work tends to be optimistic, uplifting, and emotionally resonant.',
      icon: '◈',
      type: 'practical',
      level: 2,
    },
  ],
  4: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 4 reveals your destiny as a master builder and organizer. You are meant to create lasting structures, systems, and foundations that benefit others. Your professional success comes through methodical planning, attention to detail, and consistent hard work.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional organizational abilities\n+Strong attention to detail\n+Reliable and dependable nature\n+Systematic problem-solving approach\n+Natural project management skills\n+Ability to build lasting foundations\n+Practical and realistic mindset',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Project Management: Organizing complex projects and ensuring they are completed efficiently and on time.\n\nEngineering and Architecture: Designing and building structures, systems, or processes that stand the test of time.\n\nFinancial Planning: Helping others build secure financial foundations for their future.\n\nOperations Management: Streamlining processes and improving organizational efficiency.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
    {
      id: 'creative-expression',
      title: 'Creative Expression',
      content: 'Your creativity manifests through practical applications and structured designs. You excel at creating functional beauty - whether in architecture, craftsmanship, or systematic improvements. Your artistic work tends to be precise, well-crafted, and enduring.',
      icon: '◈',
      type: 'practical',
      level: 2,
    },
  ],
  5: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 5 marks you as a dynamic communicator and adventurous spirit. You are destined for careers that offer variety, travel, and constant learning. Your professional path involves connecting with diverse people and experiences, often serving as a bridge between different worlds.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Excellent communication and networking skills\n+Adaptability and flexibility\n+Natural curiosity and learning ability\n+Gift for languages and cultural understanding\n+Persuasive and influential abilities\n+Comfort with change and new experiences\n+Ability to see multiple perspectives',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Sales and Marketing: Your persuasive abilities and people skills make you a natural at connecting products with customers.\n\nTravel and Tourism: Exploring new places and helping others discover the world.\n\nJournalism and Media: Investigating stories and communicating information to diverse audiences.\n\nConsulting: Bringing fresh perspectives to different organizations and industries.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
    {
      id: 'creative-expression',
      title: 'Creative Expression',
      content: 'Your creativity thrives on variety and exploration. You excel at combining different influences and styles to create something unique. Your artistic work often reflects your travels, experiences, and multicultural perspectives.',
      icon: '◈',
      type: 'practical',
      level: 2,
    },
  ],
  6: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 6 reveals your destiny as a natural healer and nurturer. You are meant to serve others through teaching, healing, counseling, or creating beauty in the world. Your professional path involves caring for people, communities, or causes that improve the lives of others.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Natural healing and counseling abilities\n+Strong sense of responsibility for others\n+Gift for creating harmony and beauty\n+Excellent teaching and mentoring skills\n+Ability to see potential in people\n+Natural parenting and caregiving instincts\n+Strong moral compass and ethics',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Healthcare and Healing: Nursing, therapy, alternative healing modalities where you can help others recover and thrive.\n\nEducation: Teaching at any level, from early childhood to adult education and professional development.\n\nSocial Work: Helping individuals and families navigate challenges and access resources.\n\nInterior Design/Arts: Creating beautiful, harmonious environments that nurture and inspire.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  7: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 7 marks you as a natural researcher and spiritual seeker. You are destined for careers that involve deep analysis, investigation, and the pursuit of truth. Your professional path involves uncovering hidden knowledge and sharing profound insights with others.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional analytical and research abilities\n+Natural intuition and psychic sensitivity\n+Gift for uncovering hidden truths\n+Deep thinking and philosophical nature\n+Ability to work independently for long periods\n+Natural scientific or spiritual insight\n+Talent for writing and teaching complex subjects',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Research and Analysis: Scientific research, data analysis, investigative work where you can uncover truths.\n\nSpiritual Teaching: Counseling, spiritual guidance, metaphysical practices that help others find meaning.\n\nWriting and Publishing: Sharing your insights through books, articles, or academic papers.\n\nTechnology: Software development, cybersecurity, or other fields requiring deep technical knowledge.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  8: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 8 reveals your destiny as a natural business leader and material achiever. You are meant to build organizations, manage resources, and create prosperity not just for yourself but for others. Your professional path involves mastering the material world while maintaining ethical standards.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Natural business acumen and financial insight\n+Strong organizational and executive abilities\n+Gift for seeing the big picture and long-term potential\n+Ability to motivate teams toward ambitious goals\n+Natural understanding of power dynamics\n+Talent for building sustainable systems\n+Strong sense of justice and fairness',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Executive Leadership: CEO, COO positions where you can guide large organizations toward success.\n\nFinance and Investment: Managing money, investments, or financial planning for individuals or institutions.\n\nReal Estate Development: Building and managing properties or commercial developments.\n\nLaw and Justice: Working within legal systems to ensure fairness and proper resource allocation.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  9: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 9 marks you as a natural humanitarian and universal server. You are destined to work for the greater good of humanity, often in roles that involve teaching, healing, or inspiring others on a large scale. Your professional path involves serving causes larger than yourself.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Natural compassion and understanding for all people\n+Gift for seeing universal truths and connections\n+Ability to inspire others toward higher purposes\n+Strong artistic and creative abilities\n+Natural teaching and mentoring skills\n+Wisdom and mature perspective on life\n+Ability to work with diverse groups of people',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Non-profit Leadership: Running organizations focused on humanitarian causes and social improvement.\n\nInternational Work: Diplomacy, international aid, or global initiatives that serve humanity.\n\nArts and Entertainment: Using creative expression to inspire and uplift large audiences.\n\nEducation and Philosophy: Teaching universal principles and wisdom to help others grow.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  11: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 11 reveals your destiny as an inspirational teacher and spiritual messenger. You are meant to bridge the gap between the spiritual and material worlds, often serving as a channel for higher wisdom and intuitive insights that can transform lives.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional intuitive and psychic abilities\n+Gift for inspiring and uplifting others\n+Natural ability to channel higher wisdom\n+Strong sensitivity to energy and emotions\n+Talent for teaching spiritual or metaphysical concepts\n+Ability to see potential in situations and people\n+Natural charisma and magnetic presence',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Spiritual Teaching: Life coaching, spiritual counseling, or teaching metaphysical subjects.\n\nHealing Arts: Energy healing, counseling, or alternative therapeutic modalities.\n\nInspirational Speaking: Motivating audiences through speeches, workshops, or media appearances.\n\nCreative Arts: Using artistic expression to convey spiritual messages and inspire transformation.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  22: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 22 marks you as the Master Builder, destined to create lasting structures and systems that benefit humanity on a large scale. You combine practical skills with visionary thinking to manifest ambitious projects that can change the world.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional ability to manifest large-scale visions\n+Natural leadership and organizational mastery\n+Gift for combining spiritual wisdom with practical action\n+Ability to inspire others to work toward ambitious goals\n+Strong intuition paired with methodical planning\n+Natural understanding of systems and processes\n+Talent for building things that endure',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Large-scale Development: Urban planning, major construction projects, or infrastructure development.\n\nSocial Innovation: Creating institutions or movements that address major societal needs.\n\nTechnology Leadership: Building tech companies or systems that transform how people live and work.\n\nGlobal Organizations: Leading international initiatives that create positive change worldwide.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ],
  33: [
    {
      id: 'professional-overview',
      title: 'Professional Overview',
      content: 'Your Expression Number 33 reveals your destiny as the Master Teacher, meant to serve as a beacon of unconditional love and healing for humanity. You are called to teach, heal, and inspire others through your example of compassionate service and spiritual wisdom.',
      icon: '■',
      type: 'traits',
      level: 1,
    },
    {
      id: 'natural-talents',
      title: 'Natural Talents',
      content: '+Exceptional ability to heal and nurture others\n+Natural teaching gifts and wisdom\n+Strong connection to universal love and compassion\n+Gift for inspiring spiritual growth in others\n+Ability to sacrifice personal gain for the greater good\n+Natural counseling and mentoring abilities\n+Deep understanding of human nature and potential',
      icon: '○',
      type: 'traits',
      level: 1,
    },
    {
      id: 'career-paths',
      title: 'Ideal Career Paths',
      content: 'Healing Professions: Advanced therapeutic work, counseling, or alternative healing that serves others selflessly.\n\nSpiritual Leadership: Guiding religious or spiritual communities with wisdom and compassion.\n\nEducation and Mentorship: Teaching or mentoring others in ways that foster their highest potential.\n\nHumanitarian Work: Leading charitable organizations or causes that alleviate suffering globally.',
      icon: '↑',
      type: 'themes',
      level: 2,
    },
  ]
};

export const EXPRESSION_TITLES: Record<number, string> = {
  1: 'The Innovative Leader',
  2: 'The Collaborative Partner',
  3: 'The Creative Communicator',
  4: 'The Systematic Builder',
  5: 'The Dynamic Explorer',
  6: 'The Nurturing Server',
  7: 'The Analytical Seeker',
  8: 'The Strategic Achiever',
  9: 'The Humanitarian Guide',
  11: 'The Inspirational Teacher',
  22: 'The Master Builder',
  33: 'The Divine Teacher',
};

export const getExpressionSections = (number: number): NumberSection[] => {
  return EXPRESSION_SECTIONS[number] || EXPRESSION_SECTIONS[1];
};

export const getExpressionTitle = (number: number): string => {
  return EXPRESSION_TITLES[number] || 'The Innovative Leader';
};