import { StyleSheet, Platform } from 'react-native';
import { PaymentColors } from '@/constants/paymentColors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PaymentColors.background.page,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 32,
  },
  header: {
    marginBottom: 20,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: PaymentColors.background.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PaymentColors.shadow.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  titleContainer: {
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
    color: PaymentColors.text.primary,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: PaymentColors.text.secondary,
    textAlign: 'center',
    marginTop: 8,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  securityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: PaymentColors.background.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PaymentColors.border.light,
    alignSelf: 'center',
  },
  securityText: {
    fontSize: 12,
    fontWeight: '500',
    color: PaymentColors.text.secondary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  formContainer: {
    gap: 16,
    marginBottom: 24,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: PaymentColors.text.tertiary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  textInput: {
    height: 48,
    backgroundColor: PaymentColors.background.surface,
    borderWidth: 1,
    borderColor: PaymentColors.border.medium,
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    color: PaymentColors.text.primary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  cardField: {
    height: 48,
    marginVertical: 0,
  },
  errorText: {
    fontSize: 12,
    color: PaymentColors.text.error,
    marginTop: 4,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: PaymentColors.text.tertiary,
    flex: 1,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  alternativePaymentsContainer: {
    marginBottom: 24,
    gap: 12,
  },
  alternativePaymentsText: {
    fontSize: 14,
    fontWeight: '500',
    color: PaymentColors.text.secondary,
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  alternativePaymentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    height: 56,
    backgroundColor: PaymentColors.background.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PaymentColors.border.medium,
    shadowColor: PaymentColors.shadow.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  alternativePaymentButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: PaymentColors.text.primary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  actionsContainer: {
    gap: 12,
  },
  generalError: {
    fontSize: 14,
    color: PaymentColors.text.error,
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  primaryButton: {
    height: 56,
    backgroundColor: PaymentColors.primary.main,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PaymentColors.primary.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: PaymentColors.text.onPrimary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  disabledButton: {
    backgroundColor: PaymentColors.button.disabled,
    shadowOpacity: 0.1,
    opacity: 0.6,
  },
  backLink: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  backLinkText: {
    fontSize: 16,
    fontWeight: '500',
    color: PaymentColors.primary.main,
    textDecorationLine: 'underline',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  securityDisclaimer: {
    fontSize: 12,
    lineHeight: 18,
    color: PaymentColors.text.disabled,
    textAlign: 'center',
    marginTop: 16,
    paddingHorizontal: 16,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
});
