import { StyleSheet, Platform } from 'react-native';
import { PaymentColors } from '@/constants/paymentColors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PaymentColors.background.page,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 32,
  },
  header: {
    marginBottom: 20,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: PaymentColors.background.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PaymentColors.shadow.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  iconContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  warningIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: PaymentColors.background.warning,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleContainer: {
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
    color: PaymentColors.text.primary,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  errorMessageContainer: {
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  errorMessage: {
    fontSize: 16,
    lineHeight: 24,
    color: PaymentColors.text.tertiary,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  goalSummaryCard: {
    backgroundColor: PaymentColors.background.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    shadowColor: PaymentColors.shadow.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: PaymentColors.border.light,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    color: PaymentColors.text.primary,
    marginBottom: 12,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  summaryLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: PaymentColors.text.secondary,
    flex: 1,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  summaryValue: {
    fontWeight: '600',
    color: PaymentColors.text.primary,
  },
  reassuranceContainer: {
    marginBottom: 32,
    paddingHorizontal: 16,
  },
  reassuranceText: {
    fontSize: 14,
    lineHeight: 20,
    color: PaymentColors.text.secondary,
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  noChargesText: {
    fontSize: 14,
    lineHeight: 20,
    color: PaymentColors.text.secondary,
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  actionsContainer: {
    gap: 12,
  },
  primaryButton: {
    height: 56,
    backgroundColor: PaymentColors.primary.main,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PaymentColors.primary.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: PaymentColors.text.onPrimary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  disabledButton: {
    backgroundColor: PaymentColors.button.disabled,
    shadowOpacity: 0.1,
    opacity: 0.6,
  },
  secondaryButton: {
    height: 48,
    backgroundColor: 'transparent',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: PaymentColors.border.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: PaymentColors.primary.main,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  linkButton: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  linkText: {
    fontSize: 16,
    fontWeight: '500',
    color: PaymentColors.primary.main,
    textDecorationLine: 'underline',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  cancelButton: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  cancelText: {
    fontSize: 14,
    fontWeight: '400',
    color: PaymentColors.text.disabled,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
});
